projects:
  tuapp:
    schemaPath: amplify\backend\api\tuapp\build\schema.graphql
    includes:
      - src\graphql\**\*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
